/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ElMessage: typeof import('element-plus/es').ElMessage
  const computed: typeof import('vue').computed
  const debounce: typeof import('lodash-es').debounce
  const onBeforeUnmoun: typeof import('vue').onBeforeUnmoun
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onMounted: typeof import('vue').onMounted
  const reactive: typeof import('vue').reactive
  const ref: typeof import('vue').ref
  const throttle: typeof import('lodash-es').throttle
  const useTemplateRef: typeof import('vue').useTemplateRef
  const watch: typeof import('vue').watch
}
